using System;

namespace PhialeTech.Components.Shared.Services
{
    public static class DemoWebHostShowcaseContent
    {
        public const string ReadyMessageType = "demoReady";

        public static string BuildHtml(string platformLabel)
        {
            var platform = EscapeForJavaScriptLiteral(platformLabel);

            return string.Join(Environment.NewLine, new[]
            {
                "<!doctype html>",
                "<html>",
                "<head>",
                "  <meta charset=\"utf-8\" />",
                "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
                "  <title>WebHost Showcase</title>",
                "  <style>",
                "    :root { color-scheme: dark; }",
                "    * { box-sizing: border-box; }",
                "    html, body { height: 100%; }",
                "    body { margin: 0; overflow: auto; font-family: 'Segoe UI', sans-serif; background: radial-gradient(circle at top, #17324d 0%, #0c1624 45%, #060b12 100%); color: #eef6ff; }",
                "    .shell { min-height: 100%; padding: 18px; display: grid; gap: 14px; }",
                "    .hero { display: grid; grid-template-columns: minmax(0, 1.35fr) minmax(280px, 0.65fr); gap: 14px; min-height: 520px; }",
                "    .panel { border: 1px solid rgba(148, 163, 184, 0.24); border-radius: 20px; background: rgba(8, 15, 24, 0.78); box-shadow: 0 22px 48px rgba(0, 0, 0, 0.28); overflow: hidden; }",
                "    .stage { position: relative; min-height: 520px; }",
                "    canvas { width: 100%; height: 100%; display: block; }",
                "    .overlay { position: absolute; left: 18px; right: 18px; top: 18px; display: flex; justify-content: space-between; gap: 12px; pointer-events: none; }",
                "    .chip { display: inline-flex; align-items: center; gap: 8px; padding: 8px 12px; border-radius: 999px; background: rgba(15, 23, 42, 0.74); border: 1px solid rgba(125, 211, 252, 0.25); font-size: 12px; letter-spacing: 0.02em; }",
                "    .dot { width: 8px; height: 8px; border-radius: 999px; background: #38bdf8; box-shadow: 0 0 14px rgba(56, 189, 248, 0.8); }",
                "    .sidebar { padding: 18px; display: grid; gap: 14px; align-content: start; }",
                "    h1 { margin: 0; font-size: 24px; line-height: 1.15; }",
                "    p { margin: 0; color: #cbd5e1; line-height: 1.45; }",
                "    .meta { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; }",
                "    .meta-card { padding: 12px 14px; border-radius: 14px; background: rgba(15, 23, 42, 0.68); border: 1px solid rgba(148, 163, 184, 0.18); }",
                "    .meta-card strong { display: block; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #7dd3fc; margin-bottom: 6px; }",
                "    .meta-card span { font-size: 18px; color: #f8fafc; }",
                "    .actions { display: flex; flex-wrap: wrap; gap: 10px; }",
                "    button { border: 0; border-radius: 999px; padding: 10px 16px; font-weight: 700; cursor: pointer; transition: transform 140ms ease, opacity 140ms ease; }",
                "    button:hover { transform: translateY(-1px); }",
                "    button.primary { background: linear-gradient(135deg, #38bdf8, #0ea5e9); color: #05263b; }",
                "    button.secondary { background: rgba(15, 23, 42, 0.88); color: #e2e8f0; border: 1px solid rgba(148, 163, 184, 0.24); }",
                "    pre { margin: 0; padding: 14px; min-height: 116px; border-radius: 14px; background: rgba(2, 6, 23, 0.88); color: #c4f1ff; border: 1px solid rgba(125, 211, 252, 0.12); white-space: pre-wrap; word-break: break-word; font-size: 12px; line-height: 1.4; }",
                "    @media (max-width: 920px) { .hero { grid-template-columns: 1fr; } .stage { min-height: 380px; } }",
                "  </style>",
                "</head>",
                "<body>",
                "  <div class=\"shell\">",
                "    <div class=\"hero\">",
                "      <section class=\"panel stage\">",
                "        <canvas id=\"scene\"></canvas>",
                "        <div class=\"overlay\">",
                "          <div class=\"chip\"><span class=\"dot\"></span><span id=\"overlayTitle\">Waiting for host...</span></div>",
                "          <div class=\"chip\"><span>Platform</span><strong id=\"overlayPlatform\">" + platform + "</strong></div>",
                "        </div>",
                "      </section>",
                "      <aside class=\"panel sidebar\">",
                "        <div>",
                "          <h1>JS canvas showcase on top of WebHost</h1>",
                "          <p>This scene is rendered entirely in JavaScript. The .NET host pushes scene updates, and JS can ping the host back.</p>",
                "        </div>",
                "        <div class=\"meta\">",
                "          <div class=\"meta-card\"><strong>Seed</strong><span id=\"seedValue\">1</span></div>",
                "          <div class=\"meta-card\"><strong>Rings</strong><span id=\"ringsValue\">4</span></div>",
                "          <div class=\"meta-card\"><strong>Hue</strong><span id=\"hueValue\">196</span></div>",
                "          <div class=\"meta-card\"><strong>Source</strong><span id=\"sourceValue\">JS ready</span></div>",
                "        </div>",
                "        <div class=\"actions\">",
                "          <button id=\"jsRandomize\" class=\"primary\">Randomize in JS</button>",
                "          <button id=\"pingHost\" class=\"secondary\">Ping host</button>",
                "        </div>",
                "        <pre id=\"log\">Bridge log will appear here.</pre>",
                "      </aside>",
                "    </div>",
                "  </div>",
                "  <script>",
                "    (function () {",
                "      var canvas = document.getElementById('scene');",
                "      var ctx = canvas.getContext('2d');",
                "      var logEl = document.getElementById('log');",
                "      var overlayTitle = document.getElementById('overlayTitle');",
                "      var seedValue = document.getElementById('seedValue');",
                "      var ringsValue = document.getElementById('ringsValue');",
                "      var hueValue = document.getElementById('hueValue');",
                "      var sourceValue = document.getElementById('sourceValue');",
                "      var state = { platform: '" + platform + "', seed: 1, rings: 4, hue: 196, label: 'JS ready', source: 'JS ready' };",
                "",
                "      function writeLog(message) {",
                "        logEl.textContent = message + '\\n' + logEl.textContent;",
                "      }",
                "",
                "      function resizeCanvas() {",
                "        var rect = canvas.getBoundingClientRect();",
                "        var dpr = window.devicePixelRatio || 1;",
                "        canvas.width = Math.max(320, Math.floor(rect.width * dpr));",
                "        canvas.height = Math.max(220, Math.floor(rect.height * dpr));",
                "      }",
                "",
                "      function seeded(value) {",
                "        var x = Math.sin(value) * 10000;",
                "        return x - Math.floor(x);",
                "      }",
                "",
                "      function syncMeta() {",
                "        overlayTitle.textContent = state.label;",
                "        seedValue.textContent = String(state.seed);",
                "        ringsValue.textContent = String(state.rings);",
                "        hueValue.textContent = String(state.hue);",
                "        sourceValue.textContent = state.source;",
                "      }",
                "",
                "      function applySceneUpdate(message) {",
                "        if (!message) {",
                "          return;",
                "        }",
                "",
                "        if (message.seed !== undefined) {",
                "          state.seed = Number(message.seed) || state.seed;",
                "        }",
                "",
                "        if (message.rings !== undefined) {",
                "          state.rings = Math.max(2, Number(message.rings) || state.rings);",
                "        }",
                "",
                "        if (message.hue !== undefined) {",
                "          state.hue = Number(message.hue) || state.hue;",
                "        }",
                "",
                "        if (message.label) {",
                "          state.label = String(message.label);",
                "        }",
                "",
                "        if (message.source) {",
                "          state.source = String(message.source);",
                "        }",
                "",
                "        syncMeta();",
                "      }",
                "",
                "      function drawScene(time) {",
                "        resizeCanvas();",
                "",
                "        var w = canvas.width;",
                "        var h = canvas.height;",
                "        var hue = state.hue;",
                "        var pulse = (Math.sin(time * 0.0014) + 1) * 0.5;",
                "        var cx = w * (0.22 + seeded(state.seed + 3) * 0.48);",
                "        var cy = h * (0.24 + seeded(state.seed + 7) * 0.5);",
                "",
                "        var background = ctx.createLinearGradient(0, 0, 0, h);",
                "        background.addColorStop(0, 'hsla(' + hue + ', 54%, 18%, 1)');",
                "        background.addColorStop(0.55, 'hsla(' + ((hue + 28) % 360) + ', 48%, 12%, 1)');",
        "        background.addColorStop(1, 'hsla(216, 58%, 6%, 1)');",
                "        ctx.fillStyle = background;",
                "        ctx.fillRect(0, 0, w, h);",
                "",
                "        ctx.save();",
                "        ctx.strokeStyle = 'rgba(148, 163, 184, 0.08)';",
                "        ctx.lineWidth = Math.max(1, w * 0.0014);",
                "        for (var gx = 0; gx <= w; gx += Math.max(34, Math.floor(w / 18))) {",
                "          ctx.beginPath();",
                "          ctx.moveTo(gx, 0);",
                "          ctx.lineTo(gx, h);",
                "          ctx.stroke();",
                "        }",
                "        for (var gy = 0; gy <= h; gy += Math.max(30, Math.floor(h / 16))) {",
                "          ctx.beginPath();",
                "          ctx.moveTo(0, gy);",
                "          ctx.lineTo(w, gy);",
                "          ctx.stroke();",
                "        }",
                "        ctx.restore();",
                "",
                "        ctx.save();",
                "        ctx.translate(cx, cy);",
                "        for (var ring = 0; ring < state.rings; ring++) {",
                "          var radius = Math.min(w, h) * (0.08 + ring * 0.072 + pulse * 0.012);",
                "          ctx.beginPath();",
                "          ctx.arc(0, 0, radius, 0, Math.PI * 2);",
                "          ctx.strokeStyle = 'hsla(' + ((hue + ring * 14) % 360) + ', 88%, ' + (66 - ring * 7) + '%, ' + (0.34 - ring * 0.05) + ')';",
                "          ctx.lineWidth = Math.max(1.5, radius * 0.018);",
                "          ctx.stroke();",
                "        }",
                "        ctx.restore();",
                "",
                "        ctx.save();",
                "        for (var shapeIndex = 0; shapeIndex < 6; shapeIndex++) {",
                "          var offsetX = w * (0.12 + seeded(state.seed + 21 + shapeIndex) * 0.72);",
                "          var offsetY = h * (0.14 + seeded(state.seed + 33 + shapeIndex) * 0.68);",
                "          var size = Math.min(w, h) * (0.08 + seeded(state.seed + 45 + shapeIndex) * 0.1);",
                "          ctx.beginPath();",
                "          ctx.moveTo(offsetX, offsetY - size * 0.6);",
                "          ctx.lineTo(offsetX + size * 0.72, offsetY - size * 0.15);",
                "          ctx.lineTo(offsetX + size * 0.5, offsetY + size * 0.58);",
                "          ctx.lineTo(offsetX - size * 0.56, offsetY + size * 0.52);",
                "          ctx.lineTo(offsetX - size * 0.72, offsetY - size * 0.18);",
                "          ctx.closePath();",
                "          ctx.fillStyle = 'hsla(' + ((hue + shapeIndex * 19 + 18) % 360) + ', 70%, 38%, 0.16)';",
                "          ctx.strokeStyle = 'hsla(' + ((hue + shapeIndex * 22) % 360) + ', 92%, 74%, 0.44)';",
                "          ctx.lineWidth = Math.max(1, size * 0.018);",
                "          ctx.fill();",
                "          ctx.stroke();",
                "        }",
                "        ctx.restore();",
                "",
                "        ctx.save();",
                "        var nodeCount = 8;",
                "        var points = [];",
                "        for (var nodeIndex = 0; nodeIndex < nodeCount; nodeIndex++) {",
                "          var px = w * (0.12 + seeded(state.seed + 101 + nodeIndex) * 0.76);",
                "          var py = h * (0.14 + seeded(state.seed + 151 + nodeIndex) * 0.7);",
                "          points.push({ x: px, y: py });",
                "        }",
                "        ctx.strokeStyle = 'hsla(' + ((hue + 36) % 360) + ', 88%, 72%, 0.52)';",
                "        ctx.lineWidth = Math.max(1.2, Math.min(w, h) * 0.004);",
                "        ctx.beginPath();",
                "        for (var pointIndex = 0; pointIndex < points.length; pointIndex++) {",
                "          var point = points[pointIndex];",
                "          if (pointIndex === 0) {",
                "            ctx.moveTo(point.x, point.y);",
                "          } else {",
                "            ctx.lineTo(point.x, point.y);",
                "          }",
                "        }",
                "        ctx.stroke();",
                "",
                "        for (var p = 0; p < points.length; p++) {",
                "          var current = points[p];",
                "          ctx.beginPath();",
                "          ctx.arc(current.x, current.y, Math.min(w, h) * 0.012, 0, Math.PI * 2);",
                "          ctx.fillStyle = 'hsla(' + ((hue + 8 + p * 7) % 360) + ', 100%, 76%, 0.92)';",
                "          ctx.fill();",
                "          ctx.beginPath();",
                "          ctx.arc(current.x, current.y, Math.min(w, h) * 0.024, 0, Math.PI * 2);",
                "          ctx.strokeStyle = 'hsla(' + ((hue + 8 + p * 7) % 360) + ', 100%, 76%, 0.2)';",
                "          ctx.lineWidth = Math.max(1, Math.min(w, h) * 0.003);",
                "          ctx.stroke();",
                "        }",
                "        ctx.restore();",
                "",
                "        ctx.save();",
                "        ctx.fillStyle = 'rgba(226, 232, 240, 0.86)';",
                "        ctx.font = Math.max(18, Math.floor(Math.min(w, h) * 0.032)) + 'px Segoe UI';",
                "        ctx.fillText(state.label, Math.max(24, w * 0.06), h - Math.max(40, h * 0.08));",
                "        ctx.fillStyle = 'rgba(125, 211, 252, 0.86)';",
                "        ctx.font = Math.max(12, Math.floor(Math.min(w, h) * 0.02)) + 'px Segoe UI';",
                "        ctx.fillText('Host-driven scene updates over a reusable WebHost abstraction', Math.max(24, w * 0.06), h - Math.max(18, h * 0.04));",
                "        ctx.restore();",
                "",
                "        requestAnimationFrame(drawScene);",
                "      }",
                "",
                "      window.addEventListener('phiale-webhost-bridge-ready', function () {",
                "        writeLog('bridge ready');",
                "        if (window.PhialeWebHost) {",
                "          window.PhialeWebHost.postMessage({",
                "            type: 'demoReady',",
                "            platform: state.platform,",
                "            detail: 'js showcase ready'",
                "          });",
                "        }",
                "      });",
                "",
                "      window.addEventListener('phiale-webhost-message', function (event) {",
                "        var message = event.detail || {};",
                "        if (message.type === 'scene.update') {",
                "          applySceneUpdate(message);",
                "        }",
                "",
                "        writeLog('host -> js: ' + JSON.stringify(message));",
                "      });",
                "",
                "      document.getElementById('jsRandomize').addEventListener('click', function () {",
                "        state.seed += 17;",
                "        state.label = 'JS randomized the scene';",
                "        state.source = 'JS randomize';",
                "        syncMeta();",
                "      });",
                "",
                "      document.getElementById('pingHost').addEventListener('click', function () {",
                "        if (window.PhialeWebHost) {",
                "          window.PhialeWebHost.postMessage({",
                "            type: 'demoPing',",
                "            seed: state.seed,",
                "            detail: 'ping from JS canvas demo'",
                "          });",
                "        }",
                "      });",
                "",
                "      syncMeta();",
                "      requestAnimationFrame(drawScene);",
                "    })();",
                "  </script>",
                "</body>",
                "</html>",
            });
        }

        private static string EscapeForJavaScriptLiteral(string value)
        {
            return (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("'", "\\'");
        }
    }
}
