namespace PhialeTech.DocumentEditor.Abstractions
{
    public enum DocumentEditorCommand
    {
        Undo = 0,
        Redo = 1,
        Paragraph = 2,
        Heading1 = 3,
        Heading2 = 4,
        Heading3 = 5,
        Bold = 6,
        Italic = 7,
        Underline = 8,
        Strike = 9,
        InlineCode = 10,
        BulletList = 11,
        OrderedList = 12,
        Blockquote = 13,
        HorizontalRule = 14,
        ClearFormatting = 15,
        TextColor = 16,
        HighlightColor = 17,
        FontFamily = 18,
        FontSize = 19,
        LineHeight = 20,
        AlignLeft = 21,
        AlignCenter = 22,
        AlignRight = 23,
        AlignJustify = 24,
        Link = 25,
        Image = 26,
        InsertTable = 27,
        AddColumnBefore = 28,
        AddColumnAfter = 29,
        DeleteColumn = 30,
        AddRowBefore = 31,
        AddRowAfter = 32,
        DeleteRow = 33,
        DeleteTable = 34,
        MergeCells = 35,
        SplitCell = 36,
        ToggleHeaderRow = 37,
        ToggleHeaderColumn = 38,
        Focus = 39,
        ExportHtml = 40,
        ExportMarkdown = 41,
        SaveJson = 42,
        LoadJson = 43,
    }
}
