namespace PhialeGrid.Core.Regions
{
    public static class GridRegionDefinitionCatalog
    {
        public static GridRegionDefinition[] CreateDefault()
        {
            return new[]
            {
                new GridRegionDefinition(
                    GridRegionKind.CoreGridSurface,
                    GridRegionHostKind.CoreSurface,
                    GridRegionPlacement.Center,
                    GridRegionContentKind.GridSurface,
                    GridRegionState.Open,
                    defaultSize: null,
                    minSize: null,
                    maxSize: null,
                    canCollapse: false,
                    canClose: false,
                    canResize: false,
                    canActivate: false),
                new GridRegionDefinition(
                    GridRegionKind.TopCommandRegion,
                    GridRegionHostKind.WorkspaceBand,
                    GridRegionPlacement.Top,
                    GridRegionContentKind.CommandBar,
                    GridRegionState.Open,
                    defaultSize: 52d,
                    minSize: 52d,
                    maxSize: 52d,
                    canCollapse: false,
                    canClose: true,
                    canResize: false,
                    canActivate: false),
                new GridRegionDefinition(
                    GridRegionKind.GroupingRegion,
                    GridRegionHostKind.WorkspaceBand,
                    GridRegionPlacement.Top,
                    GridRegionContentKind.GroupingDropZone,
                    GridRegionState.Open,
                    defaultSize: 56d,
                    minSize: 56d,
                    maxSize: 56d,
                    canCollapse: false,
                    canClose: true,
                    canResize: false,
                    canActivate: false),
                new GridRegionDefinition(
                    GridRegionKind.SummaryBottomRegion,
                    GridRegionHostKind.WorkspaceBand,
                    GridRegionPlacement.Bottom,
                    GridRegionContentKind.Summary,
                    GridRegionState.Open,
                    defaultSize: 56d,
                    minSize: 56d,
                    maxSize: 56d,
                    canCollapse: false,
                    canClose: true,
                    canResize: false,
                    canActivate: false),
                new GridRegionDefinition(
                    GridRegionKind.SummaryDesignerRegion,
                    GridRegionHostKind.WorkspacePanel,
                    GridRegionPlacement.Right,
                    GridRegionContentKind.ToolPane,
                    GridRegionState.Closed,
                    defaultSize: 320d,
                    minSize: 220d,
                    maxSize: 520d,
                    canCollapse: true,
                    canClose: true,
                    canResize: true,
                    canActivate: true),
                new GridRegionDefinition(
                    GridRegionKind.SideToolRegion,
                    GridRegionHostKind.WorkspacePanel,
                    GridRegionPlacement.Right,
                    GridRegionContentKind.ToolPane,
                    GridRegionState.Closed,
                    defaultSize: 320d,
                    minSize: 220d,
                    maxSize: 520d,
                    canCollapse: true,
                    canClose: true,
                    canResize: true,
                    canActivate: true),
                new GridRegionDefinition(
                    GridRegionKind.ChangePanelRegion,
                    GridRegionHostKind.WorkspacePanel,
                    GridRegionPlacement.Right,
                    GridRegionContentKind.ToolPane,
                    GridRegionState.Closed,
                    defaultSize: 320d,
                    minSize: 220d,
                    maxSize: 520d,
                    canCollapse: true,
                    canClose: true,
                    canResize: true,
                    canActivate: true),
                new GridRegionDefinition(
                    GridRegionKind.ValidationPanelRegion,
                    GridRegionHostKind.WorkspacePanel,
                    GridRegionPlacement.Left,
                    GridRegionContentKind.ToolPane,
                    GridRegionState.Closed,
                    defaultSize: 320d,
                    minSize: 220d,
                    maxSize: 520d,
                    canCollapse: true,
                    canClose: true,
                    canResize: true,
                    canActivate: true),
            };
        }
    }
}
