// PhialeGis.Library.Dsl.Validation/DslDiagnosticValidator.cs
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using PhialeGis.Library.Abstractions.Interactions;
using PhialeGis.Library.Abstractions.Modes;


// Generated by ANTLR for your grammar:
using PhialeGis.Library.Dsl; // PhialeDslLexer, PhialeDslParser
using PhialeGis.Library.Dsl.Modes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;

namespace PhialeGis.Library.Dsl.Validation
{
    /// <summary>
    /// Lightweight, editor-focused validator for the Phiale DSL.
    /// 
    /// Design:
    /// - Fast path: SLL + Bail on the entry rule (<c>command</c>) to keep typing latency low.
    /// - After a successful fast pass, detect <b>trailing garbage</b> by:
    ///     (1) scanning tokens after the parser stop index (default channel only), and
    ///     (2) if the stream exposes no tokens (lazy/EOF scenario), scanning the raw text
    ///         after the last consumed token (whitespace skipped).
    /// - On failure in the fast pass, run a slower LL parse with a collecting listener
    ///   to emit precise diagnostics and then perform the same trailing check.
    /// 
    /// Key point:
    /// <see cref="CommonTokenStream"/> is lazy; the parser may not lex beyond the entry
    /// rule. Therefore we both <see cref="CommonTokenStream.Fill"/> and have a fallback
    /// to raw-text scanning to guarantee trailing text is detected (e.g., "Zoom 2 dd").
    /// </summary>
    public sealed class DslDiagnosticValidator
    {
        /// <summary>
        /// Validates code with caret awareness (for live, low-noise editor feedback).
        /// </summary>
        /// <param name="code">The DSL code to validate.</param>
        /// <param name="caret">
        /// Zero-based caret position. When the caret is at the buffer end and the text
        /// is a single word, EOF expectation noise is suppressed.
        /// </param>
        public List<DslDiag> Validate(string code, int caret, IEditorInteractive editor, IDslContextProvider ctxProvider)
        {
            var diags = new List<DslDiag>();
            if (string.IsNullOrWhiteSpace(code))
                return diags;

            // Suppress noise when user is mid-typing a single keyword at the end.
            if (caret >= code.Length)
            {
                var trimmed = code.TrimEnd();
                if (trimmed.IndexOfAny(new[] { ' ', '\t', '\r', '\n' }) < 0 &&
                    Regex.IsMatch(trimmed, @"^[A-Za-z_]+$"))
                {
                    return diags;
                }
            }

            try
            {
                // Fast pass: SLL + Bail
                var (tokens, nextIndex) = ParseFast(code,editor, ctxProvider);

                // Trailing detection (tokens first, then raw text fallback)
                var trailing = TryGetTrailingFromTokens(tokens, nextIndex, code);
                if (trailing != null) diags.Add(trailing);
            }
            catch (ParseCanceledException)
            {
                // Slow pass: LL + default strategy with precise diagnostics
                ParseForDiagnostics(code, diags, editor, ctxProvider);

                // Suppress solitary "<EOF> expecting ..." when caret is at the end.
                if (diags.Count == 1 &&
                    diags[0].Message != null &&
                    diags[0].Message.IndexOf("<EOF>", StringComparison.OrdinalIgnoreCase) >= 0 &&
                    caret >= code.Length)
                {
                    return new List<DslDiag>();
                }
            }

            return diags;
        }

        /// <summary>
        /// Validates code without caret awareness (batch / non-interactive).
        /// </summary>
        public List<DslDiag> Validate(string code, IEditorInteractive editor, IDslContextProvider ctxProvider) => Validate(code, -1, editor, ctxProvider);

        // ===== Internals ======================================================

        /// <summary>
        /// Fast parse using SLL + Bail. Returns the token stream and the index of the
        /// next token after the parser stopped (first token not consumed).
        /// </summary>
        private static (CommonTokenStream tokens, int nextIndex) ParseFast(string code, IEditorInteractive editor, IDslContextProvider ctxProvider)
        {
            var pipe = DslPipelineFactory.Create(code, DslPipelinePurpose.Validate,editor, ctxProvider);
            var tokens = pipe.Tokens;
            var lexer = pipe.Lexer;
            var parser = pipe.Parser;
            parser.BuildParseTree = false;

            lexer.RemoveErrorListeners();
            parser.RemoveErrorListeners();
            parser.Interpreter.PredictionMode = PredictionMode.SLL;
            parser.ErrorHandler = new BailErrorStrategy();

            var entry = DslPipelineRegistry.Resolve(pipe.Context.Mode).entry;
            entry(parser);

            // Where parsing stopped (index of the next token to read)
            int nextIndex = tokens.Index;

            // Make sure the rest of the input is lexed so we can inspect it
            tokens.Fill();

            return (tokens, nextIndex);
        }

        /// <summary>
        /// Detailed parse using LL prediction and default error strategy.
        /// Also checks for trailing garbage after the parser stop index.
        /// </summary>
        private static void ParseForDiagnostics(string code, List<DslDiag> diags, IEditorInteractive editor, IDslContextProvider ctxProvider)
        {
            var pipe = DslPipelineFactory.Create(code, DslPipelinePurpose.Validate, editor, ctxProvider); 
            var tokens = pipe.Tokens;
            var lexer = pipe.Lexer;
            var parser = pipe.Parser; parser.BuildParseTree = false;

            var err = new CollectingErrorListener(diags);
            lexer.RemoveErrorListeners();
            parser.RemoveErrorListeners();
            lexer.AddErrorListener(err);  // lexical diagnostics
            parser.AddErrorListener(err); // syntactic diagnostics

            parser.Interpreter.PredictionMode = PredictionMode.LL;
            parser.ErrorHandler = new DefaultErrorStrategy();

            var entry = DslPipelineRegistry.Resolve(pipe.Context.Mode).entry;
            entry(parser);

            int nextIndex = tokens.Index;
            var trailing = TryGetTrailingFromTokens(tokens, nextIndex, code);
            if (trailing != null) diags.Add(trailing);
        }

        /// <summary>
        /// Try to detect trailing garbage using tokens (default channel only).
        /// If the stream exposes no tokens beyond <paramref name="nextIndex"/>,
        /// fall back to a raw-text scan.
        /// </summary>
        private static DslDiag TryGetTrailingFromTokens(CommonTokenStream tokens, int nextIndex, string code)
        {
            tokens.Fill(); // safe if already filled

            int n = tokens.Size; // includes EOF
            for (int i = nextIndex; i < n; i++)
            {
                var t = tokens.Get(i);
                if (t.Type == TokenConstants.EOF)
                    break;

                if (t.Channel == TokenConstants.DefaultChannel)
                {
                    int line = t.Line > 0 ? t.Line : 1;
                    int col = t.Column + 1;
                    int len =
                        (t.StopIndex >= t.StartIndex)
                            ? Math.Max(1, t.StopIndex - t.StartIndex + 1)
                            : Math.Max(1, (t.Text?.Length ?? 1));

                    return new DslDiag(
                        severity: "error",
                        message: "Unexpected token after the end of command.",
                        line: line,
                        column: col,
                        length: len);
                }
            }

            // Token stream did not reveal any token after the command: use raw text.
            return TryGetTrailingByText(code, tokens, nextIndex);
        }

        /// <summary>
        /// Raw-text fallback for trailing detection. Computes the character position
        /// immediately after the last consumed token and scans the original code
        /// (skipping whitespace). Highlights the first contiguous non-whitespace chunk.
        /// </summary>
        private static DslDiag TryGetTrailingByText(string code, CommonTokenStream tokens, int nextIndex)
        {
            if (string.IsNullOrEmpty(code)) return null;

            // Character index after the last consumed token
            int startChar = 0;
            if (nextIndex > 0)
            {
                var lastTok = tokens.Get(nextIndex - 1);
                if (lastTok != null && lastTok.StopIndex >= 0)
                    startChar = lastTok.StopIndex + 1;
            }

            // Skip whitespace
            int i = startChar;
            while (i < code.Length && char.IsWhiteSpace(code[i])) i++;

            if (i >= code.Length) return null; // nothing after the command

            // Take the first contiguous non-whitespace chunk as "garbage"
            int j = i;
            while (j < code.Length && !char.IsWhiteSpace(code[j])) j++;

            // Compute 1-based line/column for 'i'
            int line = 1, col = 1;
            for (int k = 0; k < i; k++)
            {
                if (code[k] == '\n')
                {
                    line++;
                    col = 1;
                }
                else if (code[k] != '\r')
                {
                    col++;
                }
            }

            int length = Math.Max(1, j - i);
            return new DslDiag(
                severity: "error",
                message: "Unexpected text after the end of command.",
                line: line,
                column: col,
                length: length);
        }

        /// <summary>
        /// Error listener collecting both lexical and syntactic diagnostics
        /// into a shared list. Positions are 1-based (editor-friendly).
        /// </summary>
        private sealed class CollectingErrorListener :
            BaseErrorListener,           // parser (IToken)
            IAntlrErrorListener<int>     // lexer (int)
        {
            private readonly List<DslDiag> _diags;

            public CollectingErrorListener(List<DslDiag> diags)
            {
                _diags = diags ?? throw new ArgumentNullException(nameof(diags));
            }

            // Parser errors (syntactic)
            public override void SyntaxError(
                TextWriter output,
                IRecognizer recognizer,
                IToken offendingSymbol,
                int line,
                int charPositionInLine,
                string msg,
                RecognitionException e)
            {
                int len = 1;

                if (offendingSymbol != null)
                {
                    var text = offendingSymbol.Text;
                    if (!string.IsNullOrEmpty(text))
                    {
                        len = Math.Max(1, text.Length);
                    }
                    else if (offendingSymbol.StopIndex >= offendingSymbol.StartIndex)
                    {
                        len = Math.Max(1, offendingSymbol.StopIndex - offendingSymbol.StartIndex + 1);
                    }
                }

                _diags.Add(new DslDiag(
                    severity: "error",
                    message: msg ?? "syntax error",
                    line: line,
                    column: charPositionInLine + 1,
                    length: len));
            }

            // Lexer errors (lexical)
            void IAntlrErrorListener<int>.SyntaxError(
                TextWriter output,
                IRecognizer recognizer,
                int offendingSymbol,
                int line,
                int charPositionInLine,
                string msg,
                RecognitionException e)
            {
                _diags.Add(new DslDiag(
                    severity: "error",
                    message: msg ?? "lexical error",
                    line: line,
                    column: charPositionInLine + 1,
                    length: 1));
            }
        }
    }

    /// <summary>
    /// Minimal diagnostic DTO for editor consumption.
    /// Lines and columns are 1-based; <see cref="Length"/> is clamped to ≥ 1.
    /// </summary>
    public sealed class DslDiag
    {
        public DslDiag(string severity, string message, int line, int column, int length)
        {
            Severity = severity ?? "error";
            Message = message ?? string.Empty;
            Line = line;
            Column = column;
            Length = Math.Max(1, length);
        }

        /// <summary>Diagnostic severity (e.g., "error", "warning").</summary>
        public string Severity { get; }

        /// <summary>Human-readable diagnostic message.</summary>
        public string Message { get; }

        /// <summary>1-based line number.</summary>
        public int Line { get; }

        /// <summary>1-based column number.</summary>
        public int Column { get; }

        /// <summary>Highlight length in characters.</summary>
        public int Length { get; }
    }
}
