# GenerateDslFiles.ps1  — PS 5.1 compatible, no here-strings, UTF-8 no BOM

param (
    [string]$inputLexerFile = "PhialeDslLexer.g4",
    [string]$inputParserFile = "PhialeDslParser.g4",
    [string]$outputDir = "../Generated",
    [string]$namespace = "PhialeGis.Library.Dsl",
    # If you don't have antlr4.cmd in PATH, point to the JAR:
    [string]$antlrJar = "antlr-4.13.1-complete.jar"
)

function Get-ScriptDir {
    if ($PSScriptRoot) { return $PSScriptRoot }
    return (Split-Path -Parent $MyInvocation.MyCommand.Path)
}
function Resolve-Rel([string]$p) {
    if ([string]::IsNullOrWhiteSpace($p)) { return $null }
    if ([System.IO.Path]::IsPathRooted($p)) { return $p }
    return (Join-Path (Get-ScriptDir) $p)
}
function Write-Utf8NoBom([string]$path, [string]$content) {
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($path, $content, $enc)
}
function Rel([string]$base, [string]$path) {
    try {
        $u = New-Object System.Uri((Resolve-Path $path).Path)
        $b = New-Object System.Uri((Resolve-Path $base).Path + [System.IO.Path]::DirectorySeparatorChar)
        return $b.MakeRelativeUri($u).ToString()
    } catch { return $path }
}

$scriptDir   = Get-ScriptDir
$outDirAbs   = Resolve-Rel $outputDir
$lexerR4Abs  = Resolve-Rel $inputLexerFile
$parserG4Abs = Resolve-Rel $inputParserFile

if (!(Test-Path $outDirAbs)) { New-Item -ItemType Directory -Path $outDirAbs | Out-Null }
if (!(Test-Path $lexerR4Abs)) { throw "Brak pliku leksykera: $lexerR4Abs" }
if (!(Test-Path $parserG4Abs)) { throw "Brak pliku parsera: $parserG4Abs" }

# ===== 1) Read .r4 and build PhialeDslLexer.g4 (lowercased keywords, skip duplicate header) =====
$lexerText = [System.IO.File]::ReadAllText($lexerR4Abs)
$lines = $lexerText -split "`r?`n"

$headerRegex = '^\s*(lexer|parser)?\s*grammar\b'
$kwPattern   = '^\s*(\w+)\s*:\s*''([^'']+)''\s*;\s*$'

# lower -> original map (for Transition.cs)
$prefMap = New-Object 'System.Collections.Generic.Dictionary[string,string]' ([StringComparer]::OrdinalIgnoreCase)

# Build the map first (unique by lower-cased literal)
$allMatches = [System.Text.RegularExpressions.Regex]::Matches($lexerText, '(\w+)\s*:\s*''([^'']+)''\s*;', 'IgnoreCase')
foreach ($m in $allMatches) {
    $lit = $m.Groups[2].Value
    if ($lit) {
        $low = $lit.ToLowerInvariant()
        if (-not $prefMap.ContainsKey($low)) { $prefMap[$low] = $lit }
    }
}

# Compose .g4
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// <auto-generated>")
[void]$sb.AppendLine("// This file is intentionally placed under the 'Generated' folder.")
[void]$sb.AppendLine("// Why it exists here")
[void]$sb.AppendLine("// ------------------")
[void]$sb.AppendLine("// The generator transforms Grammar/PhialeDslLexer.g4 into a concrete ANTLR4 lexer grammar")
[void]$sb.AppendLine("// with lower-cased literals to enforce case-insensitive parsing. ANTLR requires the")
[void]$sb.AppendLine("// lexer .g4 (and its resulting *.tokens) to be available alongside the parser .g4")
[void]$sb.AppendLine("// (via -lib) so the parser can resolve token names during code generation.")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// Consequences")
[void]$sb.AppendLine("// ------------")
[void]$sb.AppendLine("// • Do NOT edit this file. Edit the source .g4 files in Grammar folder and re-run the generator.")
[void]$sb.AppendLine("// • Removing or relocating this file may break ANTLR generation (missing tokens).")
[void]$sb.AppendLine("// • Keeping it in 'Generated' makes build scripts deterministic and isolates artifacts.")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// SCM note")
[void]$sb.AppendLine("// --------")
[void]$sb.AppendLine("// You may choose to exclude 'Generated/' from version control. The file is reproducible")
[void]$sb.AppendLine("// from sources by running GenerateDslFiles.ps1.")
[void]$sb.AppendLine("// </auto-generated>")

[void]$sb.AppendLine("lexer grammar PhialeDslLexer;")
foreach ($line in $lines) {
    if ([System.Text.RegularExpressions.Regex]::IsMatch($line, $headerRegex)) { continue }
    $m = [System.Text.RegularExpressions.Regex]::Match($line, $kwPattern)
    if ($m.Success) {
        $tok   = $m.Groups[1].Value
        $lit   = $m.Groups[2].Value
        $lower = $lit.ToLowerInvariant()
        [void]$sb.AppendLine("$tok : '$lower' ;")
    } else {
        [void]$sb.AppendLine($line)
    }
}

$lexerG4Path = Join-Path $outDirAbs "PhialeDslLexer.g4"
Write-Utf8NoBom $lexerG4Path $sb.ToString()
Write-Host ("Generated lexer g4: " + (Rel $scriptDir $lexerG4Path))

# ===== 2) Generate PhialeDslTransition.cs (UTF-8 no BOM) =====
$cs = New-Object System.Text.StringBuilder
[void]$cs.AppendLine("// This file was automatically generated from " + [System.IO.Path]::GetFileName($lexerR4Abs) + " at " + (Get-Date -Format "yyyy-MM-dd HH:mm:ss"))
[void]$cs.AppendLine("// Do not edit manually - changes will be overwritten by the generator!")
[void]$cs.AppendLine("using System;")
[void]$cs.AppendLine("using System.Collections.Generic;")
[void]$cs.AppendLine("")
[void]$cs.AppendLine("namespace $namespace")
[void]$cs.AppendLine("{")
[void]$cs.AppendLine("    public static class PhialeDslTransition")
[void]$cs.AppendLine("    {")
[void]$cs.AppendLine("        public static string GetPreferredDisplay(string lit)")
[void]$cs.AppendLine("        {")
[void]$cs.AppendLine("            if (string.IsNullOrEmpty(lit)) return lit;")
[void]$cs.AppendLine("            string v;")
[void]$cs.AppendLine("            if (PreferredDisplay.TryGetValue(lit.ToLowerInvariant(), out v)) return v;")
[void]$cs.AppendLine("            return lit;")
[void]$cs.AppendLine("        }")
[void]$cs.AppendLine("")
[void]$cs.AppendLine("        private static readonly Dictionary<string, string> PreferredDisplay =")
[void]$cs.AppendLine("            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)")
[void]$cs.AppendLine("        {")

# ---- CHANGE: emit only entries where preferred differs from the lower-cased key (case-sensitive check) ----
foreach ($kv in $prefMap.GetEnumerator()) {
    if ($kv.Value -ceq $kv.Key) { continue }  # skip identical entries like '(' -> '(' or 'and' -> 'and'
    [void]$cs.AppendLine("            { `"$($kv.Key)`", `"$($kv.Value)`" },")
}

[void]$cs.AppendLine("        };")
[void]$cs.AppendLine("    }")
[void]$cs.AppendLine("}")

$transitionPath = Join-Path $outDirAbs "PhialeDslTransition.cs"
Write-Utf8NoBom $transitionPath $cs.ToString()
Write-Host ("Generated transition: " + (Rel $scriptDir $transitionPath) + "  (entries: " + $prefMap.Count + " → filtered)")

# ===== 3) ANTLR — first lexer.g4, then parser.g4 with -lib (so it can find *.tokens) =====
$antlrCmd = $null
try { $antlrCmd = (Get-Command antlr4 -ErrorAction SilentlyContinue) } catch { }
$useJava = $false
$javaJarPath = $null
if ($antlrCmd -eq $null) {
    $jarCandidate = Resolve-Rel $antlrJar
    if (-not (Test-Path $jarCandidate)) {
        throw "Nie znaleziono 'antlr4' w PATH ani JAR: $jarCandidate"
    }
    $useJava = $true
    $javaJarPath = $jarCandidate
}

$pkg = $namespace
$out = $outDirAbs
$lib = $outDirAbs
$lexerArg  = $lexerG4Path
$parserArg = $parserG4Abs

if (-not $useJava) {
    & $antlrCmd.Path -Dlanguage=CSharp -package $pkg -visitor -listener -o $out $lexerArg
    if ($LASTEXITCODE -ne 0) { throw "ANTLR (lexer) zwrócił kod $LASTEXITCODE" }

    & $antlrCmd.Path -Dlanguage=CSharp -package $pkg -visitor -listener -o $out -lib $lib $parserArg
    if ($LASTEXITCODE -ne 0) { throw "ANTLR (parser) zwrócił kod $LASTEXITCODE" }
} else {
    & java "-jar" $javaJarPath -Dlanguage=CSharp -package $pkg -visitor -listener -o $out $lexerArg
    if ($LASTEXITCODE -ne 0) { throw "ANTLR (lexer/JAR) zwrócił kod $LASTEXITCODE" }

    & java "-jar" $javaJarPath -Dlanguage=CSharp -package $pkg -visitor -listener -o $out -lib $lib $parserArg
    if ($LASTEXITCODE -ne 0) { throw "ANTLR (parser/JAR) zwrócił kod $LASTEXITCODE" }
}

Write-Host "ANTLR generation complete."
